baseURL: https://preachit.reguel.de

languageCode: de-De
title: Predigtbewertung
theme: hugo-feedback-theme

params:
  emailbridge: https://emailbridge.reguel.de
  showKeyword: false


languageCode: de-De
defaultContentLanguage: de
defaultContentLanguageInSubdir: true

languages:
  de:
    languageName: Deutsch
    params:
      linkedin: https://linkedin.com/whoever
    title: Predigtbewertung
    weight: 1
  en:
    languageName: English
    params:
      linkedin: https://linkedin.com/fr/whoever
    title: Sermon Evaluation
    weight: 2
  ru:
    languageName: Русский
    params:
      linkedin: https://linkedin.com/fr/whoever
    title: Оценка проповеди
    weight: 3
